### ISSUE TITLE
Provides support for JTB, the Java Tree Builder

### ISSUE THREAD

**Issue by zosrothko** [javacc/javaccPlugin#27]
Hi

Using [JTB](https://java.net/projects/jtb) is quite useful for building a Abstract Syntax Tree (and an Abstract Semantic Tree). Could you plan to add the support of JTB in your plugin (as much as the Eclipse JavaCC plugin support it)

Thanks
##

**Comment by zosrothko** [comment]
Just a simple question: There is a bundled AntLR plugin in gradle. Did you think about releasing your plugin as a bundled plugin with gradle?

**Comment by johnmartel** [comment]
This plugin is released through the [Gradle Plugins Portal](https://plugins.gradle.org/). As I am not a Gradle member, I don't think I can actually bundle my plugin with Gradle. That is not important, as it is available through the standard plugin mechanism.

**Comment by zosrothko** [comment]
Sure it is not important.... but one has to import your plugin explicitly while it would be easier if your plugin was bundled with gradle... it is just a way to improve the usability and to place JavaCC at the same level as AntLR

**Comment by zbynek** [comment]
The link in ticket description is dead. http://compilers.cs.ucla.edu/jtb/ is still active, last release of the tool is from 2016 https://mvnrepository.com/artifact/edu.purdue.cs/jtb
