### ISSUE TITLE
Support for gradle buildCache

### ISSUE THREAD

**Issue by ramonwirsch** [javacc/javaccPlugin#42]
Hi,
I would like to implement support for gradles buildCache, but am not familiar enough with JavaCC to be sure about all the parameters on which the outputs depend.

Right off the bat, it seems like the `programArguments` task property would need to be declared as an actual input property for that.
Are there any other dependencies not already declared?

If there are no unforseen further parameters that influence the output I'm happy to patch it and create a pull request, as it would greatly speed up my builds.

**Comment by johnmartel** [comment]
Thanks for the request. I have been off on other duties, but now have time for some changes in this plugin. I am in the process of migrating to the latest and greatest Gradle version, and will make the necessary changes to improve build times as per the new available features. Expect a release soon.

**Comment by zbynek** [comment]
The necessary annotation was added in https://github.com/javacc/javaccPlugin/commit/911eeb29bd2474eb0a48ade99f66611fd797a283 -- please reopen if there is still an issue with this.
