### ISSUE TITLE
Does this plugin support javacc 4.0v? 

### ISSUE THREAD

**Issue by BoopathySrinivasan** [javacc/javaccPlugin#50]
Hi,

 Now we are migrating our legacy product over there we need to use javacc 4.0 version to convert .jjt files

dependencies {
    javacc 'net.java.dev.javacc:javacc:4.0'
}
when we use the above dependencies it throws below error

> Task :llt:compileJjtree FAILED
Java Compiler Compiler Version 4.0 (Tree Builder)
(type "jjtree" with no arguments for help)
Exception in thread "main" java.lang.NullPointerException
	at org.javacc.parser.Options.setCmdLineOption(Unknown Source)
	at org.javacc.jjtree.JJTree.main(Unknown Source)
	at org.javacc.jjtree.Main.main(Unknown Source)

FAILURE: Build failed with an exception.

**Comment by zbynek** [comment]
The acceptance tests are passing with Javacc 4.1 (released 2008) but not 4.0 (released 2006). Probably a good idea to update your jjt files at least a bit, but I'll check if this has a simple fix.
