### ISSUE TITLE
Change plugin id to match JavaCC organization

### ISSUE THREAD

**Issue by kpitt** [javacc/javaccPlugin#52]
The original author of this plugin used his company domain (`ca.coglinc`) in the Gradle Portal plugin id and the Maven Central group id. Many thanks to @johnmartel for all his hard work in developing this plugin.

Now that the JavaCC organization is taking over maintenance of the plugin and preparing for a 3.0.0 major release, this seems like the appropriate time to update the plugin ids to align with the other artifacts produced by the JavaCC team. The exact ids are still in the process of being finalized, but the current proposal is `org.javacc.plugin` for the Maven group id, `javacc-gradle-plugin` for the Maven artifact id, and `org.javacc.plugin.javacc-gradle-plugin` for the Gradle plugin id. This naming convention aligns with the existing JavaCC Maven plugin (`org.javacc.plugin:javacc-maven-plugin` on Maven Central).

**Comment by zbynek** [comment]
@zosrothko now the README refers to plugin name and version that have not yet been published. Is there anything blocking a release?

**Comment by zosrothko** [comment]
@zbynek I do not manage this repository.  I gave you the admin access to this repository so you can edit, maintain and publish whatever you want. Welcome on board!

**Comment by zbynek** [comment]
@zosrothko I tried publishing the plugin with the new group ID and got this reply from Gradle team:

> Please prove ownership of the "[javacc.org](http://javacc.org/)" domain by adding a TXT record with value "gradle-verification=AKU1MS5NV2OT294IFQC1BMPKBUGNO" to your DNS

Can you please set the DNS record?

**Comment by zosrothko** [comment]
@zbynek I cannot fulfill your request because I do not know anything to javacc.org. Please contact @new-javacc which is the owner of JavaCC as well as the owner of `javacc.org`.

**Comment by kaikalur** [comment]
@martinswanson can you please take a look?

**Comment by zosrothko** [comment]
@kaikalur the request is related to the DNS that manages the URI javacc.rg. Thus the action is more on Kesav than anybodyelse. By the way, I think that the administration of the javacc.org URI should be passed to a admin member of the GitHub javacc organization.

**Comment by zbynek** [comment]
@kaikalur @zosrothko meanwhile I asked for alternative ways of verification and the suggestion was

> Pls. create a public repository named "gradle-portal-verification-0KU9MKAK" under the user "javacc" which you can delete once the first plugin version is approved.

which I hope one of you can do more easily than the DNS setting. 

Before we actually push the release I would like to ask you to decide/confirm what the correct plugin ID should be, see https://github.com/javacc/javaccPlugin/pull/55#issuecomment-1371155587 and compare with [other plugin IDs](https://plugins.gradle.org/).

**Comment by zosrothko** [comment]
@zbynek public repository created: [https://github.com/javacc/gradle-portal-verification-0KU9MKAK](https://github.com/javacc/gradle-portal-verification-0KU9MKAK)

Reguarding the name of the javacc gradle plugin, I am in favor to remove the 'plugin' part in its name.

**Comment by zbynek** [comment]
@zosrothko thanks, so do you agree with `org.javacc.javacc` or do you have a different suggestion?

**Comment by kaikalur** [comment]
I thought Kesav handed over the work to Martin. Cc'd him here so he can do it if needed.Thanks!On Jan 8, 2023 11:58 PM, Francis ANDRE ***@***.***> wrote:
@kaikalur the request is related to the DNS that manages the URI javacc.rg. Thus the action is more on Kesav than anybodyelse. By the way, I think that the administration of the javacc.org URI should be passed to a admin member of the GitHub javacc organization.

**Comment by zosrothko** [comment]
@zbynek That's fine for me: `org.javacc.javacc`

**Comment by kaikalur** [comment]
Sure if it works!On Jan 9, 2023 9:05 AM, Francis ANDRE ***@***.***> wrote:
@zbynek That's fine for me: org.javacc.javacc
