### ISSUE TITLE
plugin does not generate classes for package: "com.softwareag.rules.functions.parser"

### ISSUE THREAD

**Issue by sveri** [javacc/javaccPlugin#63]
Hi,

I have a pretty sizeable jj definition, that contains this part:

```
PARSER_BEGIN(JCCFunctionsParser)
package com.softwareag.rules.functions.parser;

public class JCCFunctionsParser
{}

PARSER_END(JCCFunctionsParser)
```

Now, when I run the gradle plugin with `gradlew compileJavacc` the expected java classes are not generated.
After some trying out, all I could figure out, that the package name is the problem.
Basically every package combination I tried works, like:
- package com.softwareag.rules.function.parser;
- package com.softwareag.rules.functions.parserr;
- package com.parser;
- package com.softwareag.rules.parser;

But the original one: package com.softwareag.rules.functions.parser; does not work. I don't see any errors during the gradle build and no suspicious output. 

Any idea what might be wrong here? While changing the package name is an option, I would like to know why this fails with this specific package name.

**Comment by zbynek** [comment]
Can you please share a minimal example that would show this error?

**Comment by sveri** [comment]
Hi, I made it as small as this:

```

PARSER_BEGIN(JCCFunctionsParser)
package com.softwareag.rules.functions.parser;

public class JCCFunctionsParser
{}

PARSER_END(JCCFunctionsParser)

TOKEN:
{
   < DIGIT: ["0"-"9"] >
}

```

Behaviour is the same as described in my first comment.

**Comment by zbynek** [comment]
thanks, I meant a minimal project (maybe a github repo) so that one can see in which subfolder is your parser located, what version of the plugin is used and how is it configured etc.

**Comment by zbynek** [comment]
I'm closing this, feel free to reopen if you have more information on how to reproduce the issue.
